image: python:3.11-bullseye

variables:
  GIT_LFS_SKIP_SMUDGE: "1"

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: always
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
    when: always
  - when: never

before_script:
  - pip install -r requirements-base.txt
  - export PYTHONPATH="$PYTHONPATH:$(pwd)"

linters:
  script:
    - pip install pylint ruff
    - python -m pylint --rcfile=.pylintrc $(git ls-files "*.py" | grep -v "test")
    - ruff check

unit_tests:
  script:
    - apt-get update
    - pip install pytest pytest-mock
    - pytest test/robobase/unit test/roboimpl/unit

e2e_tests:
  script:
    - apt-get update
    - apt install -y lsof netcat ffmpeg
    - wget https://gitlab.com/video-representations-extractor/video-representations-extractor/-/raw/master/resources/test_video.mp4 -P test/e2e/video-udp-screenshot 2>/dev/null
    - bash test/e2e/run_all.sh
