image: python:3.11-bullseye

variables:
  GIT_LFS_SKIP_SMUDGE: "1"

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: always
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
    when: always
  - when: never

before_script:
  - pip install -r requirements-base.txt
  - pip install pylint ruff

pylint:
  script:
    - python -m pylint --rcfile=.pylintrc $(git ls-files "*.py" | grep -v "test/\|examples/")

ruff:
  script:
    - ruff check
