image: python:3.11-bullseye

variables:
  GIT_LFS_SKIP_SMUDGE: "1"

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: always
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
    when: always
  - when: never

before_script:
  - pip install -r requirements-drones.txt

linters:
  script:
    - pip install pylint ruff
    - python -m pylint --rcfile=.pylintrc $(git ls-files "*.py" | grep -v "test")
    - ruff check

unit_tests:
  script:
    - apt-get update -y
    - apt install python3-tk
    - export PYTHONPATH="$PYTHONPATH:$(pwd)"
    - pip install pytest pytest-mock
    - pytest test/unit
